-- Tworzenie sekwencji
CREATE SEQUENCE seq_DostawcaID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_PaliwoID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_DystrybutorID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_KlientID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_KartaKredytowaID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_TransakcjaID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_FakturaID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_ZamowienieID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_SzczegolyZamowieniaID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_PracownikID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_ZmianaID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_PracownikZmianaID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_PremiePracownikowID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_SzczegolyTransakcjiID START WITH 1 INCREMENT BY 1;