--SEKWENCJE

CREATE SEQUENCE seq_DostawcyID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_PaliwaID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_DystrybutorID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_KlientID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_KartaKredytowaID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_TransakcjaID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_FakturaID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_ZamówienieID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_SzczegółyZamówieniaID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_PracownikID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_ZmianaID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_PracownikZmianaID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_PremiePracownikówID START WITH 1 INCREMENT BY 1;